// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type IncidentReport struct {
	Date           string  `json:"date"`
	ID             string  `json:"id"`
	InjuryLocation string  `json:"injuryLocation"`
	Gender         string  `json:"gender"`
	AgeGroup       string  `json:"ageGroup"`
	IncidentType   string  `json:"incidentType"`
	DaysLost       string  `json:"daysLost"`
	Plant          string  `json:"plant"`
	ReportType     string  `json:"reportType"`
	Shift          string  `json:"shift"`
	Department     string  `json:"department"`
	IncidentCost   string  `json:"incidentCost"`
	Wkday          *string `json:"wkday,omitempty"`
	Month          int     `json:"month"`
	Year           int     `json:"year"`
	IsActive       bool    `json:"is_active"`
	IsDeleted      bool    `json:"is_deleted"`
}

type Mutation struct {
}

type Query struct {
}

type AddReportInput struct {
	Date           *string `json:"date,omitempty"`
	ID             *string `json:"id,omitempty"`
	InjuryLocation *string `json:"injuryLocation,omitempty"`
	Gender         *string `json:"gender,omitempty"`
	AgeGroup       *string `json:"ageGroup,omitempty"`
	IncidentType   *string `json:"incidentType,omitempty"`
	DaysLost       *string `json:"daysLost,omitempty"`
	Plant          *string `json:"plant,omitempty"`
	ReportType     *string `json:"reportType,omitempty"`
	Shift          *string `json:"shift,omitempty"`
	Department     *string `json:"department,omitempty"`
	IncidentCost   *string `json:"incidentCost,omitempty"`
	Wkday          *string `json:"wkday,omitempty"`
	Month          *int    `json:"month,omitempty"`
	Year           *int    `json:"year,omitempty"`
	IsActive       *bool   `json:"is_active,omitempty"`
	IsDeleted      *bool   `json:"is_deleted,omitempty"`
}

type ReportCreated struct {
	Message string `json:"message"`
}
